name: ThePitUltimate
version: 4.2.5
description: A Bukkit mini-game plugin.
authors: [ KleeLoveLife, Rabbit0w0, Araykal ]

api-version: 1.8
main: cn.charlotte.pit.ThePit
load: POSTWORLD
depend: [ PlayerPoints, LuckPerms, ProtocolLib ]
softdepend: [ WorldEdit, FastAsyncWorldEdit ]