name: ThePitUltimate
version: 4.01
description: A Bukkit mini-game plugin.
authors: [ KleeLoveLife, Rabbit0w0, Araykal ]

api-version: 1.8
main: cn.charlotte.pit.ThePit
load: POSTWORLD
softdepend: [ ProtocolLib, WorldEdit, FastAsyncWorldEdit, PlayerPoints, LuckPerms ]