Name: ThePitUltimate
Version: 4.4.6
EntryClass: net.mizukilab.pit.Loader
EntryPoint: start
InfPort: false
KeepClasses:
  - "^net\\.mizukilab\\.pit\\.enchantment..*$"
  - "^net\\.mizukilab\\.pit\\.item..*$"
